name: Update Language Statistics

on:
  schedule:
    - cron: '0 9 * * *'  # Run at 9:00 AM UTC
    - cron: '0 21 * * *' # Run at 9:00 PM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install txt-lang-stats
        run: |
          ls -a
          pip install ./txt-lang-stats

      - name: Update README.md
        env:
            TXLST_GITHUB_TOKEN: ${{ secrets.TXLST_GITHUB_TOKEN }}
            TXLST_GITHUB_USERNAME: "eeriemyxi"
            TXLST_INCLUDE_FORKS: "False"
            TXLST_BLACKLIST_LANGS: '{"CSS", "Shell", "Emacs Lisp", "KakouneScript"}'
            TXLST_SYMBOLS: '("+", "-", "=", "~", "×", "&", "*", ".")'
        run: |
          txt-lang-stats --insert-into README-TEMPLATE.md > README.md

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update language statistics"
          push_options: '--force-with-lease'
